name: 'Build docs'
description: 'Trigger docs workflow'
inputs:
  token:
    description: 'Access token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Trigger docs build
      env:
        DISPATCH_API: https://api.github.com/repos/Breakthrough-Energy/docs/actions/workflows/2386877/dispatches
      run: |
        curl -XPOST -H "Authorization: token ${{ inputs.token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/json" ${{ env.DISPATCH_API }} \
        --data '{"ref": "refs/heads/master"}'
